config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users
  
  resources :hokkaidos, only: [:index, :show, :count] , shallow: true do
    resources :hokkaido_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :touhokus, only: [:index, :show] , shallow: true do
    resources :touhoku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kantous, only: [:index, :show], shallow: true do
    resources :kantou_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :koushinetsus, only: [:index, :show], shallow: true do
    resources :koushinetsu_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :toukais, only: [:index, :show], shallow: true do
    resources :toukai_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :hokurikus, only: [:index, :show], shallow: true do
    resources :hokuriku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kansais, only: [:index, :show], shallow: true do
    resources :kansai_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :sanyos, only: [:index, :show], shallow: true do
    resources :sanyo_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :sanins, only: [:index, :show], shallow: true do
    resources :sanin_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :shikokus, only: [:index, :show], shallow: true do
    resources :shikoku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kyushus, only: [:index, :show], shallow: true do
    resources :kyushu_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :okinawas, only: [:index, :show], shallow: true do
    resources :okinawa_reviews, only: [:index, :new, :create, :destroy]
  end
end

app/controllers/hokkaido_reviews_controller.rb
class HokkaidoReviewsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :crete, :destroy, :edit, :update] 
  before_action :correct_user, only: [:destroy] 
  
  def index
    @hokkaido = Hokkaido.find(params[:hokkaido_id])
    @hokkaido_reviews = @hokkaido.hokkaido_reviews.all.page(params[:page])
  end

  def new
    @hokkaido = Hokkaido.find(params[:hokkaido_id])
    @hokkaido_review = @hokkaido.hokkaido_reviews.new
  end

  def create
    @hokkaido = Hokkaido.find(params[:hokkaido_id])
    @hokkaido_review = @hokkaido.hokkaido_reviews.new(hokkaido_review_params)
    @hokkaido_review.user_id = current_user.id
    if @hokkaido_review.save
      flash[:success] = 'レビュー が正常に投稿されました'
      redirect_to hokkaido_hokkaido_reviews_path
    else
      flash.now[:danger] = 'レビュー が投稿されませんでした'
      render :new
    end
  end

  def destroy
    @hokkaido_review.destroy
    flash[:success] = 'レビューを削除しました。'
    redirect_back(fallback_location: root_url)
  end

  private
  
  def set_hokkaido_review
    @hokkaido = Hokkaido.find(params[:hokkaido_id])
    @hokkaido_review = @hokkaido.hokkaido_reviews.find(params[:id])
  end
  # Strong Parameter
  def hokkaido_review_params
    params.require(:hokkaido_review).permit(:content, :evaluation)
  end
  
  def correct_user
    @hokkaido_review = current_user.hokkaido_reviews.find_by(id: params[:id])
    unless @hokkaido_review
      redirect_to root_path
    end
  end
end

app/views/hokkaido_reviews/_hokkaido_reviews.html.erb
<div class="area hokkaido">
  <ul class="media-list">
    <div>
      <%= link_to 'レビューする', new_hokkaido_hokkaido_review_path(@hokkaido, @hokkaido_review), class: 'btn btn-primary' %>
    </div><br />
    <div class="panel panel-default">
      <h2>レビュー一覧</h2>
      <%= link_to '戻る', @hokkaido, class: 'btn btn-primary' %>
      <% @hokkaido_reviews.each do |hokkaido_review| %>
        <% user = hokkaido_review.user %>
        <div class="media">
          <div class="media-left">
            <img class="media-object img-rounded" src="<%= gravatar_url(hokkaido_review.user, options = { size: 50 }) %>" alt="">
          </div>
          <div class="media-body">
            <div>
              <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= hokkaido_review.created_at %></span>
            </div>
            <div>
              <p>評価：<%= hokkaido_review.evaluation %></p>
              <p><%= hokkaido_review.content %></p>
            </div>
            <div>
              <% if current_user == hokkaido_review.user %>
                <%= link_to 'このレビューを削除する', hokkaido_review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @hokkaido_reviews %>
  </ul>
</div>

app/views/hokkaido_reviews/index.html.erb
<%= render 'hokkaido_reviews/hokkaido_reviews', hokkaido_reviews: @hokkaido_reviews %>

app/views/hokkaido_reviews/new.html.erb
<div class="area hokkaido">
  <h1><%= @hokkaido.title %></h1>
  <ul class="media-list">
    <div class="row">
      <aside class="col-xs-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <li class="media">
              <h2>レビューを投稿する</h2>
              <%= form_for ([@hokkaido, @hokkaido_review]) do |f| %>
                <%= f.label :evaluation, '評価(1~5)' %>
                <%= f.text_field :evaluation, class: 'form-control', rows: 2 %>
                <%= f.label :content, 'レビュー' %>
                <%= f.text_area :content, class: 'form-control', rows: 5 %>
                <br />
                <%= f.submit '投稿' , class: 'btn btn-success btn-lg'%>
              <% end %>
            </li>
          </div>  
        </div>
      </aside>
    </div>
  </ul>
</div>