config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users
  
  resources :hokkaidos, only: [:index, :show, :count] , shallow: true do
    resources :hokkaido_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :touhokus, only: [:index, :show] , shallow: true do
    resources :touhoku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kantous, only: [:index, :show], shallow: true do
    resources :kantou_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :koushinetsus, only: [:index, :show], shallow: true do
    resources :koushinetsu_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :toukais, only: [:index, :show], shallow: true do
    resources :toukai_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :hokurikus, only: [:index, :show], shallow: true do
    resources :hokuriku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kansais, only: [:index, :show], shallow: true do
    resources :kansai_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :sanyos, only: [:index, :show], shallow: true do
    resources :sanyo_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :sanins, only: [:index, :show], shallow: true do
    resources :sanin_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :shikokus, only: [:index, :show], shallow: true do
    resources :shikoku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kyushus, only: [:index, :show], shallow: true do
    resources :kyushu_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :okinawas, only: [:index, :show], shallow: true do
    resources :okinawa_reviews, only: [:index, :new, :create, :destroy]
  end
end

app/controllers/koushinetsu_reviews_controller.rb
class KoushinetsuReviewsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :crete, :destroy] 
  before_action :correct_user, only: [:destroy] 
  
  def index
    @koushinetsu = Koushinetsu.find(params[:koushinetsu_id])
    @koushinetsu_reviews = @koushinetsu.koushinetsu_reviews.all.page(params[:page])
  end

  def new
    @koushinetsu = Koushinetsu.find(params[:koushinetsu_id])
    @koushinetsu_review = @koushinetsu.koushinetsu_reviews.new
  end

  def create
    @koushinetsu = Koushinetsu.find(params[:koushinetsu_id])
    @koushinetsu_review = @koushinetsu.koushinetsu_reviews.new(koushinetsu_review_params)
    @koushinetsu_review.user_id = current_user.id
    if @koushinetsu_review.save
      flash[:success] = 'レビュー が正常に投稿されました'
      redirect_to koushinetsu_koushinetsu_reviews_path
    else
      flash.now[:danger] = 'レビュー が投稿されませんでした'
      render :new
    end
  end

  def destroy
    @koushinetsu_review.destroy
    flash[:success] = 'レビューを削除しました。'
    redirect_back(fallback_location: root_url)
  end

  private
  
  def set_koushinetsu_review
    @koushinetsu = Koushinetsu.find(params[:koushinetsu_id])
    @koushinetsu_review = @koushinetsu.koushinetsu_reviews.find(params[:id])
  end
  # Strong Parameter
  def koushinetsu_review_params
    params.require(:koushinetsu_review).permit(:content, :evaluation)
  end
  
  def correct_user
    @koushinetsu_review = current_user.koushinetsu_reviews.find_by(id: params[:id])
    unless @koushinetsu_review
      redirect_to root_path
    end
  end
end

app/views/koushinetsu_reviews/_koushinetsu_reviews.html.erb
<div class="area koushinetsu">
  <ul class="media-list">
    <div>
      <%= link_to 'レビューする', new_koushinetsu_koushinetsu_review_path(@koushinetsu, @koushinetsu_review), class: 'btn btn-primary' %>
    </div><br />
    <div class="panel panel-default">
      <h2>レビュー一覧</h2>
      <%= link_to '戻る', @koushinetsu, class: 'btn btn-primary' %>
      <% @koushinetsu_reviews.each do |koushinetsu_review| %>
        <% user = koushinetsu_review.user %>
        <li class="media">
          <div class="media-left">
            <img class="media-object img-rounded" src="<%= gravatar_url(koushinetsu_review.user, options = { size: 50 }) %>" alt="">
          </div>
          <div class="media-body">
            <div>
              <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= koushinetsu_review.created_at %></span>
            </div>
            <div>
              <p>評価：<%= koushinetsu_review.evaluation %></p>
              <p><%= koushinetsu_review.content %></p>
            </div>
            <div>
              <% if current_user == koushinetsu_review.user %>
                <%= link_to 'このレビューを削除する', koushinetsu_review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </div>
    <%= paginate @koushinetsu_reviews %>
  </ul>
</div>

app/views/koushinetsu_reviews/index.html.erb
<%= render 'koushinetsu_reviews/koushinetsu_reviews', koushinetsu_reviews: @koushinetsu_reviews %>

app/views/koushinetsu_reviews/new.html.erb
<div class="area koushinetsu">
  <h1><%= @koushinetsu.title %></h1>
  <ul class="media-list">
    <div class="row">
      <aside class="col-xs-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <li class="media">
              <h2>レビューを投稿する</h2>
              <%= form_for ([@koushinetsu, @koushinetsu_review]) do |f| %>
                <%= f.label :evaluation, '評価(1~5)' %>
                <%= f.text_field :evaluation, class: 'form-control', rows: 2 %>
                <%= f.label :content, 'レビュー' %>
                <%= f.text_area :content, class: 'form-control', rows: 5 %>
                <br />
                <%= f.submit '投稿' , class: 'btn btn-success btn-lg'%>
              <% end %>
            </li>
          </div>  
        </div>
      </aside>
    </div>
  </ul>
</div>