config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users
  
  resources :hokkaidos, only: [:index, :show, :count] , shallow: true do
    resources :hokkaido_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :touhokus, only: [:index, :show] , shallow: true do
    resources :touhoku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kantous, only: [:index, :show], shallow: true do
    resources :kantou_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :koushinetsus, only: [:index, :show], shallow: true do
    resources :koushinetsu_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :toukais, only: [:index, :show], shallow: true do
    resources :toukai_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :hokurikus, only: [:index, :show], shallow: true do
    resources :hokuriku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kansais, only: [:index, :show], shallow: true do
    resources :kansai_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :sanyos, only: [:index, :show], shallow: true do
    resources :sanyo_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :sanins, only: [:index, :show], shallow: true do
    resources :sanin_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :shikokus, only: [:index, :show], shallow: true do
    resources :shikoku_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :kyushus, only: [:index, :show], shallow: true do
    resources :kyushu_reviews, only: [:index, :new, :create, :destroy]
  end
  
  resources :okinawas, only: [:index, :show], shallow: true do
    resources :okinawa_reviews, only: [:index, :new, :create, :destroy]
  end
end

app/models/hokkaido.rb
class Hokkaido < ApplicationRecord
  has_many :hokkaido_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/hokuriku.rb
class Hokuriku < ApplicationRecord
  has_many :hokuriku_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/kansai.rb
class Kansai < ApplicationRecord
  has_many :kansai_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/kansai_review.rb
class KansaiReview < ApplicationRecord
  belongs_to :user
  belongs_to :kansai
    
  validates :user_id, presence: true
  validates :kansai_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/kantou.rb
class Kantou < ApplicationRecord
  has_many :kantou_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/kantou_review.rb
class KantouReview < ApplicationRecord
  has_many :kantou_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/koushinetsu.rb
class Koushinetsu < ApplicationRecord
  has_many :koushinetsu_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/kyushu.rb
class Kyushu < ApplicationRecord
  has_many :kyushu_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/kyushu_review.rb
class KyushuReview < ApplicationRecord
  belongs_to :user
  belongs_to :kyushu
  
  validates :user_id, presence: true
  validates :kyushu_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/okinawa.rb
class Okinawa < ApplicationRecord
  has_many :okinawa_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/sanin.rb
class Sanin < ApplicationRecord
  has_many :hokuriku_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/sanin_review.rb
class SaninReview < ApplicationRecord
  belongs_to :user
  belongs_to :sanin
  
  validates :user_id, presence: true
  validates :sanin_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/sanyo.rb
class Sanyo < ApplicationRecord
  has_many :sanyo_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/sanyo_review.rb
class SanyoReview < ApplicationRecord
  belongs_to :user
  belongs_to :sanyo
  
  validates :user_id, presence: true
  validates :sanyo_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/shikoku.rb
class Shikoku < ApplicationRecord
  has_many :shikoku_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/touhoku.rb
class Touhoku < ApplicationRecord
  has_many :touhoku_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/toukai.rb
class Toukai < ApplicationRecord
  has_many :toukai_reviews
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/toukai_review.rb
class ToukaiReview < ApplicationRecord
  belongs_to :user
  belongs_to :toukai
  
  validates :user_id, presence: true
  validates :toukai_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :hokkaido_reviews
  has_many :touhoku_reviews
  has_many :kantou_reviews
  has_many :toukai_reviews
  has_many :hokuriku_reviews
  has_many :koushinetsu_reviews
  has_many :kansai_reviews
  has_many :sanyo_reviews
  has_many :sanin_reviews
  has_many :shikoku_reviews
  has_many :kyushu_reviews
  has_many :okinawa_reviews
end

app/controllers/sanin_reviews_controller.rb
class SaninReviewsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :crete, :destroy] 
  before_action :correct_user, only: [:destroy] 
  
  def index
    @sanin = Sanin.find(params[:sanin_id])
    @sanin_reviews = @sanin.sanin_reviews.all.page(params[:page])
  end

  def new
    @sanin = Sanin.find(params[:sanin_id])
    @sanin_review = @sanin.sanin_reviews.new
  end

  def create
    @sanin = Sanin.find(params[:sanin_id])
    @sanin_review = @sanin.sanin_reviews.new(sanin_review_params)
    @sanin_review.user_id = current_user.id
    if @sanin_review.save
      flash[:success] = 'レビュー が正常に投稿されました'
      redirect_to sanin_sanin_reviews_path
    else
      flash.now[:danger] = 'レビュー が投稿されませんでした'
      render :new
    end
  end

  def destroy
    @sanin_review.destroy
    flash[:success] = 'レビューを削除しました。'
    redirect_back(fallback_location: root_url)
  end

  private
  
  def set_sanin_review
    @sanin = Sanin.find(params[:sanin_id])
    @sanin_review = @sanin.sanin_reviews.find(params[:id])
  end
  # Strong Parameter
  def sanin_review_params
    params.require(:sanin_review).permit(:content, :evaluation)
  end
  
  def correct_user
    @sanin_review = current_user.sanin_reviews.find_by(id: params[:id])
    unless @sanin_review
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/sanin_reviews/_sanin_reviews.html.erb
<div class="area sanin">
  <ul class="media-list">
    <div>
      <%= link_to 'レビューする', new_sanin_sanin_review_path(@sanin, @sanin_review), class: 'btn btn-primary' %>
    </div><br />
    <div class="panel panel-default">
      <h2>レビュー一覧</h2>
      <%= link_to '戻る', @sanin, class: 'btn btn-primary' %>
      <% @sanin_reviews.each do |sanin_review| %>
        <% user = sanin_review.user %>
        <li class="media">
          <div class="media-left">
            <img class="media-object img-rounded" src="<%= gravatar_url(sanin_review.user, options = { size: 50 }) %>" alt="">
          </div>
          <div class="media-body">
            <div>
              <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= sanin_review.created_at %></span>
            </div>
            <div>
              <p>評価：<%= sanin_review.evaluation %></p>
              <p><%= sanin_review.content %></p>
            </div>
            <div>
              <% if current_user == sanin_review.user %>
                <%= link_to 'このレビューを削除する', sanin_review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </div>
    <%= paginate @sanin_reviews %>
  </ul>
</div>

app/views/sanin_reviews/index.html.erb
<%= render 'sanin_reviews/sanin_reviews', sanin_reviews: @sanin_reviews %>

app/views/sanin_reviews/new.html.erb
<div class="area sanin">
  <h1><%= @sanin.title %></h1>
  <ul class="media-list">
    <div class="row">
      <aside class="col-xs-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <li class="media">
              <h2>レビューを投稿する</h2>
              <%= form_for ([@sanin, @sanin_review]) do |f| %>
                <%= f.label :evaluation, '評価(1~5)' %>
                <%= f.text_field :evaluation, class: 'form-control', rows: 2 %>
                <%= f.label :content, 'レビュー' %>
                <%= f.text_area :content, class: 'form-control', rows: 5 %>
                <br />
                <%= f.submit '投稿' , class: 'btn btn-success btn-lg'%>
              <% end %>
            </li>
          </div>  
        </div>
      </aside>
    </div>
  </ul>
</div>